/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    screens: {
      sm: '480px',
      md: '768px',
      lg: '992px',
      xl: '1200px',
    },
    extend: {
      colors: {
        'bg-base': 'var(--bg-base)',
        'bg-pitch': 'var(--bg-pitch)',
        'bg-vignette': 'var(--bg-vignette)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        'surface-line': 'var(--surface-line)',
        'text-hi': 'var(--text-hi)',
        'text-mid': 'var(--text-mid)',
        'text-lo': 'var(--text-lo)',
        'text-onaccent': 'var(--text-onAccent)',
        accent: 'var(--accent)',
        'accent-hi': 'var(--accent-hi)',
        'accent-dim': 'var(--accent-dim)',
        data: 'var(--data)',
        'data-dim': 'var(--data-dim)',
        'pos-gk': 'var(--pos-gk)',
        'pos-def': 'var(--pos-def)',
        'pos-mid': 'var(--pos-mid)',
        'pos-fwd': 'var(--pos-fwd)',
        ok: 'var(--ok)',
        warn: 'var(--warn)',
        error: 'var(--error)',
      },
      fontFamily: {
        display: ['Oswald', 'Black Han Sans', 'Noto Sans KR', 'sans-serif'],
        body: ['Noto Sans KR', 'Oswald', 'sans-serif'],
        mono: ['Roboto Mono', 'Noto Sans KR', 'monospace'],
      },
      borderRadius: {
        sm: 'var(--r-sm)',
        md: 'var(--r-md)',
        lg: 'var(--r-lg)',
        xl: 'var(--r-xl)',
        pill: 'var(--r-pill)',
      },
      boxShadow: {
        1: 'var(--sh-1)',
        card: 'var(--sh-2)',
        'card-hover': 'var(--sh-3)',
        'glow-accent': 'var(--glow-accent)',
        'glow-soft': 'var(--glow-soft)',
        'glow-data': 'var(--glow-data)',
      },
      spacing: {
        13: '52px',
        18: '72px',
      },
    },
  },
  plugins: [],
}
